package com.jjt.manager.pojo;

import java.io.Serializable;
import java.util.Date;

public class Item implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.title
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sell_point
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private String sellPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.num
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.barcode
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.image
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.cid
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.status
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.created
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.updated
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.title
     *
     * @return the value of item.title
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.title
     *
     * @param title the value for item.title
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sell_point
     *
     * @return the value of item.sell_point
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sell_point
     *
     * @param sellPoint the value for item.sell_point
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.num
     *
     * @return the value of item.num
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.num
     *
     * @param num the value for item.num
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.barcode
     *
     * @return the value of item.barcode
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.barcode
     *
     * @param barcode the value for item.barcode
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.image
     *
     * @return the value of item.image
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.image
     *
     * @param image the value for item.image
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.cid
     *
     * @return the value of item.cid
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.cid
     *
     * @param cid the value for item.cid
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.status
     *
     * @return the value of item.status
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.status
     *
     * @param status the value for item.status
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created
     *
     * @return the value of item.created
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created
     *
     * @param created the value for item.created
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.updated
     *
     * @return the value of item.updated
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.updated
     *
     * @param updated the value for item.updated
     *
     * @mbg.generated Sun Aug 25 19:10:54 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}