package com.jjt.manager.mapper;

import com.jjt.manager.pojo.ContentCat;
import com.jjt.manager.pojo.ContentCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    long countByExample(ContentCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int deleteByExample(ContentCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int insert(ContentCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int insertSelective(ContentCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    List<ContentCat> selectByExample(ContentCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    ContentCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ContentCat record, @Param("example") ContentCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int updateByExample(@Param("record") ContentCat record, @Param("example") ContentCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int updateByPrimaryKeySelective(ContentCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_cat
     *
     * @mbg.generated Sat Sep 14 19:24:56 CST 2019
     */
    int updateByPrimaryKey(ContentCat record);
}