package com.jjt.manager.mapper;

import com.jjt.manager.pojo.ItemCat;
import com.jjt.manager.pojo.ItemCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    long countByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int deleteByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int insert(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int insertSelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    List<ItemCat> selectByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    ItemCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int updateByExample(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int updateByPrimaryKeySelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Aug 25 16:40:01 CST 2019
     */
    int updateByPrimaryKey(ItemCat record);
}